# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJA9VVYZ-G8DktB3utzkviDpcsyud2hO
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import cv2
import os
import gdown

# ── Page Config ───────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Brain Tumor Detector",
    page_icon="🧠",
    layout="wide"
)

# ── Custom CSS ────────────────────────────────────────────────────────────
st.markdown("""
    <style>
    .main { background-color: #0f1117; }
    .stApp { background-color: #0f1117; }
    .title {
        font-size: 3rem;
        font-weight: 800;
        text-align: center;
        background: linear-gradient(90deg, #4fc3f7, #7c4dff);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.2rem;
    }
    .subtitle {
        text-align: center;
        color: #888;
        font-size: 1rem;
        margin-bottom: 2rem;
    }
    .result-box {
        background: #1e1e2e;
        border-radius: 16px;
        padding: 24px;
        border: 1px solid #333;
        margin-top: 10px;
    }
    .class-glioma     { color: #ef5350; font-size: 2rem; font-weight: 700; }
    .class-meningioma { color: #ffa726; font-size: 2rem; font-weight: 700; }
    .class-notumor    { color: #66bb6a; font-size: 2rem; font-weight: 700; }
    .class-pituitary  { color: #ab47bc; font-size: 2rem; font-weight: 700; }
    .confidence-text  { color: #aaa; font-size: 1rem; margin-top: 4px; }
    .warning-box {
        background: #1a1a2e;
        border-left: 4px solid #ffa726;
        padding: 12px 16px;
        border-radius: 8px;
        color: #ccc;
        font-size: 0.85rem;
        margin-top: 20px;
    }
    </style>
""", unsafe_allow_html=True)

# ── Constants ─────────────────────────────────────────────────────────────
MODEL_PATH   = "bestmodel_finetuned.keras"
IMAGE_SIZE   = 224
CLASSES      = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']

CLASS_META = {
    'Glioma': {
        'icon':        '🔴',
        'css_class':   'class-glioma',
        'color':       '#ef5350',
        'description': 'Aggressive tumor arising from glial cells in the brain or spine. Requires urgent specialist review.',
        'action':      'Immediate referral to a neuro-oncologist is strongly advised.',
    },
    'Meningioma': {
        'icon':        '🟡',
        'css_class':   'class-meningioma',
        'color':       '#ffa726',
        'description': 'Typically benign, slow-growing tumor arising from the meninges surrounding the brain.',
        'action':      'Regular monitoring recommended. Consult a neurosurgeon for evaluation.',
    },
    'No Tumor': {
        'icon':        '🟢',
        'css_class':   'class-notumor',
        'color':       '#66bb6a',
        'description': 'No tumor detected in this MRI scan.',
        'action':      'No immediate action required. Continue routine check-ups.',
    },
    'Pituitary': {
        'icon':        '🟣',
        'css_class':   'class-pituitary',
        'color':       '#ab47bc',
        'description': 'Tumor located in the pituitary gland, which can affect hormone regulation.',
        'action':      'Endocrinology and neurosurgery consultation recommended.',
    },
}

# ── Model Loading ─────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_model():
    """
    Load model from disk.
    If the model file is missing and you stored it on Google Drive,
    uncomment the gdown block below and paste your file ID.
    """
    # ── Option A: model is in the same folder as app.py (recommended) ──
    if not os.path.exists(MODEL_PATH):

        # ── Option B: download from Google Drive at runtime ─────────────
        # Uncomment these 3 lines and paste your Google Drive file ID:
        # FILE_ID = "YOUR_GOOGLE_DRIVE_FILE_ID_HERE"
        # st.info("Downloading model from Google Drive... this may take a minute.")
        # gdown.download(f"https://drive.google.com/uc?id={FILE_ID}", MODEL_PATH, quiet=False)

        st.error("Model file not found. Place 'bestmodel_finetuned.keras' in the same folder as app.py")
        st.stop()

    model = tf.keras.models.load_model(MODEL_PATH)
    return model

# ── Preprocessing ─────────────────────────────────────────────────────────
def preprocess_image(image: Image.Image) -> np.ndarray:
    """
    Resize → convert to numpy → apply MobileNetV2 preprocess_input.
    This scales pixels to [-1, 1] which matches how the model was trained.
    DO NOT use rescale=1./255 here — that would break predictions.
    """
    img = np.array(image.convert("RGB"))
    img = cv2.resize(img, (IMAGE_SIZE, IMAGE_SIZE))
    img = tf.keras.applications.mobilenet_v2.preprocess_input(img.astype(np.float32))
    return np.expand_dims(img, axis=0)  # shape: (1, 224, 224, 3)

# ── Prediction ────────────────────────────────────────────────────────────
def predict(model, image: Image.Image):
    input_tensor = preprocess_image(image)
    probs        = model.predict(input_tensor, verbose=0)[0]  # shape: (4,)
    pred_index   = int(np.argmax(probs))
    pred_class   = CLASSES[pred_index]
    confidence   = float(probs[pred_index]) * 100
    return pred_class, confidence, probs

# ══════════════════════════════════════════════════════════════════════════
# UI
# ══════════════════════════════════════════════════════════════════════════

# ── Header ────────────────────────────────────────────────────────────────
st.markdown('<div class="title">🧠 Brain Tumor Detector</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Upload a brain MRI scan · Powered by MobileNetV2 · 90.62% Test Accuracy</div>', unsafe_allow_html=True)
st.divider()

# ── Load model (runs once, cached) ────────────────────────────────────────
with st.spinner("Loading model..."):
    model = load_model()
st.success("✅ Model loaded successfully!", icon="✅")

st.divider()

# ── Upload Section ────────────────────────────────────────────────────────
uploaded_file = st.file_uploader(
    "Upload a Brain MRI Image",
    type=["jpg", "jpeg", "png"],
    help="Upload a T1-weighted brain MRI scan in JPG or PNG format."
)

# ── Prediction Section ────────────────────────────────────────────────────
if uploaded_file is not None:
    image = Image.open(uploaded_file)

    st.divider()
    left_col, right_col = st.columns([1, 1], gap="large")

    # ── Left: MRI Image ───────────────────────────────────────────────────
    with left_col:
        st.subheader("📷 Uploaded MRI Scan")
        st.image(image, use_column_width=True, caption=uploaded_file.name)

    # ── Right: Results ────────────────────────────────────────────────────
    with right_col:
        st.subheader("🔬 Analysis Result")

        with st.spinner("Analyzing MRI scan..."):
            pred_class, confidence, all_probs = predict(model, image)

        meta = CLASS_META[pred_class]

        # Result box
        st.markdown(f"""
            <div class="result-box">
                <div style="font-size:2.5rem;">{meta['icon']}</div>
                <div class="{meta['css_class']}">{pred_class}</div>
                <div class="confidence-text">Confidence: <strong style="color:{meta['color']}">{confidence:.1f}%</strong></div>
                <hr style="border-color:#333; margin: 12px 0;">
                <p style="color:#ccc; font-size:0.95rem;">{meta['description']}</p>
                <p style="color:#aaa; font-size:0.85rem;"><b>Recommended Action:</b> {meta['action']}</p>
            </div>
        """, unsafe_allow_html=True)

    # ── Probability Bar Chart ─────────────────────────────────────────────
    st.divider()
    st.subheader("📊 All Class Probabilities")

    prob_cols = st.columns(4)
    for i, cls in enumerate(CLASSES):
        prob = float(all_probs[i]) * 100
        m    = CLASS_META[cls]
        with prob_cols[i]:
            st.metric(label=f"{m['icon']} {cls}", value=f"{prob:.1f}%")
            st.progress(prob / 100)

    # ── Disclaimer ────────────────────────────────────────────────────────
    st.markdown("""
        <div class="warning-box">
            ⚠️ <strong>Medical Disclaimer:</strong> This tool is for educational and research purposes only.
            It is <u>not</u> a substitute for professional medical diagnosis.
            Always consult a qualified radiologist or physician for clinical decisions.
        </div>
    """, unsafe_allow_html=True)

else:
    # ── Placeholder when no image uploaded ────────────────────────────────
    st.markdown("""
        <div style="text-align:center; padding: 60px 20px; color: #555;">
            <div style="font-size: 4rem;">🧠</div>
            <div style="font-size: 1.2rem; margin-top: 12px;">Upload an MRI scan above to begin analysis</div>
            <div style="font-size: 0.9rem; margin-top: 8px; color: #444;">Supported formats: JPG, JPEG, PNG</div>
        </div>
    """, unsafe_allow_html=True)

# ── Sidebar ───────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("🧠 About This App")
    st.markdown("""
    This app uses a fine-tuned **MobileNetV2** deep learning model to classify brain MRI scans into 4 categories.
    """)

    st.divider()
    st.subheader("📈 Model Performance")
    st.metric("Test Accuracy",  "90.62%")
    st.metric("No Tumor",       "100.0%")
    st.metric("Pituitary",      "98.3%")
    st.metric("Meningioma",     "89.8%")
    st.metric("Glioma",         "74.5%")

    st.divider()
    st.subheader("🏷️ Classes")
    st.markdown("""
    | Icon | Class | Type |
    |------|-------|------|
    | 🔴 | Glioma | Malignant |
    | 🟡 | Meningioma | Usually Benign |
    | 🟢 | No Tumor | Normal |
    | 🟣 | Pituitary | Benign |
    """)

    st.divider()
    st.subheader("⚙️ Model Details")
    st.markdown("""
    - **Architecture:** MobileNetV2
    - **Input Size:** 224 × 224 px
    - **Training:** 5,600 images
    - **Fine-tuned Layers:** Top 30
    - **Framework:** TensorFlow / Keras
    """)

    st.divider()
    st.caption("Brain Tumor Detection Project · 2026")
